// utils/dummydata.js

const genres = ['Action', 'Horror', 'Drama', 'Komedi', 'Animasi', 'Sci-Fi'];
const mediaTypes = ['Movie', 'Series'];

const films = [
  { id: 1, title: 'Inception', genres: ['Action', 'Sci-Fi'], mediaType: 'Movie' },
  { id: 2, title: 'The Dark Knight', genres: ['Action'], mediaType: 'Movie' },
  { id: 3, title: 'Forrest Gump', genres: ['Drama'], mediaType: 'Movie' },
  { id: 4, title: 'Mr. Bean Holiday', genres: ['Komedi'], mediaType: 'Movie' },
  { id: 5, title: 'The Matrix', genres: ['Action', 'Sci-Fi'], mediaType: 'Movie' },
  { id: 6, title: 'Titanic', genres: ['Drama'], mediaType: 'Movie' },
  { id: 7, title: 'Frozen', genres: ['Animasi'], mediaType: 'Movie' },
  { id: 8, title: 'Harry Potter and the Sorcerer Stone', genres: ['Animasi'], mediaType: 'Movie' },
  { id: 9, title: 'The Conjuring', genres: ['Horror'], mediaType: 'Movie' },
  { id: 10, title: 'Stranger Things', genres: ['Horror'], mediaType: 'Series' },
  { id: 11, title: 'Black Mirror', genres: ['Sci-Fi'], mediaType: 'Series' },
  { id: 12, title: 'Narcos', genres: ['Drama'], mediaType: 'Series' },
  { id: 13, title: 'The Avengers', genres: ['Action'], mediaType: 'Movie' },
  { id: 14, title: 'Guardians of the Galaxy', genres: ['Action', 'Sci-Fi'], mediaType: 'Movie' },
  { id: 15, title: 'Get Out', genres: ['Horror'], mediaType: 'Movie' },
  { id: 16, title: 'Joker', genres: ['Drama'], mediaType: 'Movie' },
  { id: 17, title: 'La La Land', genres: ['Drama'], mediaType: 'Movie' },
  { id: 18, title: 'Up', genres: ['Animasi'], mediaType: 'Movie' },
  { id: 19, title: 'Your Name', genres: ['Animasi', 'Drama'], mediaType: 'Movie' },
  { id: 20, title: 'Train to Busan', genres: ['Horror'], mediaType: 'Movie' },
  { id: 21, title: 'Coco', genres: ['Animasi'], mediaType: 'Movie' },
  { id: 22, title: 'Parasite', genres: ['Drama'], mediaType: 'Movie' },
  { id: 23, title: 'Demon Slayer', genres: ['Animasi'], mediaType: 'Series' },
  { id: 24, title: 'Death Note', genres: ['Animasi'], mediaType: 'Series' },
  { id: 25, title: 'The Witcher', genres: ['Action', 'Fantasy'], mediaType: 'Series' },
  { id: 26, title: 'Money Heist', genres: ['Action'], mediaType: 'Series' },
  { id: 27, title: 'Breaking Bad', genres: ['Drama'], mediaType: 'Series' },
  { id: 28, title: 'Friends', genres: ['Komedi'], mediaType: 'Series' },
  { id: 29, title: 'The Office', genres: ['Komedi'], mediaType: 'Series' },
  { id: 30, title: 'The Crown', genres: ['Drama'], mediaType: 'Series' },
  { id: 31, title: 'It', genres: ['Horror'], mediaType: 'Movie' },
  { id: 32, title: 'The Exorcist', genres: ['Horror'], mediaType: 'Movie' },
  { id: 33, title: 'Mad Max: Fury Road', genres: ['Action'], mediaType: 'Movie' },
  { id: 34, title: 'Gladiator', genres: ['Action', 'Drama'], mediaType: 'Movie' },
  { id: 35, title: 'Black Panther', genres: ['Action'], mediaType: 'Movie' },
  { id: 36, title: 'Edge of Tomorrow', genres: ['Action', 'Sci-Fi'], mediaType: 'Movie' },
  { id: 37, title: 'Stranger', genres: ['Drama'], mediaType: 'Series' },
  { id: 38, title: 'Sherlock', genres: ['Drama'], mediaType: 'Series' },
  { id: 39, title: 'Avatar', genres: ['Action', 'Sci-Fi'], mediaType: 'Movie' },
  { id: 40, title: 'Avengers: Endgame', genres: ['Action'], mediaType: 'Movie' },
  { id: 41, title: 'Violet Evergarden', genres: ['Drama', 'Animasi'], mediaType: 'Series' },
  { id: 42, title: 'One Punch Man', genres: ['Animasi', 'Sci-Fi'], mediaType: 'Series' },
  { id: 43, title: 'Naruto', genres: ['Animasi', 'Action'], mediaType: 'Series' },
  { id: 44, title: 'Death Stranding', genres: ['Sci-Fi'], mediaType: 'Movie' },
  { id: 45, title: 'Interstellar', genres: ['Sci-Fi', 'Drama'], mediaType: 'Movie' },
  { id: 46, title: 'The Handmaid’s Tale', genres: ['Drama'], mediaType: 'Series' },
  { id: 47, title: 'Mindhunter', genres: ['Drama'], mediaType: 'Series' },
  { id: 48, title: 'Chernobyl', genres: ['Drama'], mediaType: 'Series' },
  { id: 49, title: 'Blade Runner 2049', genres: ['Sci-Fi'], mediaType: 'Movie' },
  { id: 50, title: 'Logan', genres: ['Action', 'Drama'], mediaType: 'Movie' },
];

module.exports = { genres, mediaTypes, films };
